channels:
  - bioconda
  - r
  - conda-forge
  - bushmanlab
  - defaults
dependencies:
  - snakemake
  - blat
  - bwa
  - samtools
  - graphviz
  - r=3.4.1
  - r-base
  - r-argparse
  - r-pander
  - r-yaml
  - r-tidyverse
  - r-magrittr
  - r-data.table
  - r-matrix
  - r-igraph
  - r-rmarkdown >= 1.8
  - r-knitr
  - r-reshape2
  - r-scales
  - r-rcolorbrewer
  - r-devtools
  - bioconductor-biocgenerics
  - bioconductor-iranges
  - bioconductor-genomicranges
  - bioconductor-hiannotator
  - bioconductor-biostrings
  - bioconductor-shortread
  - bioconductor-rsamtools
  - bioconductor-bsgenome
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
