__default__ :
    nCPUs     : 1
    memory    : 4000
    resources : "\"span[hosts=1]\""
    name      : "JOBNAME.{rule}.{wildcards}"
    output    : "{RUN_DIR}/logs/{rule}.{wildcards}.out"
    error     : "{RUN_DIR}/logs/{rule}.{wildcards}.err"
